name: Drive Sync
on:
  workflow_dispatch:
env:
  SCRIPT_URL: https://gist.githubusercontent.com/subekti404dev/3297651428c31b813c06857f88f19365/raw/7c9b1d0bf75536c2acf9ec852ec67a38d7d021ef/drive_init_config
  SOURCE_DIR: "design-code"
  TARGET_DIR: ""
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
       
        - uses: subekti404dev/github-action-vault-secret@v1
          with:
            base-url: "${{ secrets.VAULT_BASE_URL }}"
            token: "${{ secrets.VAULT_TOKEN }}"
            path: "subekti404dev/test-actions"
            key: "DOTENV_DRIVE_SYNC"
            to-file: ".env"
          
        - name: Download Script && Install
          run: curl "$SCRIPT_URL" | bash
          
        - name: Mount Drive
          run:  bash mount.sh
          
        - run: cd drive1 && ls -lah
        - run: cd drive2 && ls -lah
        
        - run: rsync -auvr --progress drive1/"$SOURCE_DIR" drive2/"$TARGET_DIR"
