name: Drive Sync
on:
  workflow_dispatch:
env:
  SCRIPT_URL: https://gist.githubusercontent.com/subekti404dev/3297651428c31b813c06857f88f19365/raw/7c9b1d0bf75536c2acf9ec852ec67a38d7d021ef/drive_init_config
  SOURCE_DIR: drive1/design-code
  TARGET_DIR: drive2
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
       
        - name: Write .env File
          run: echo '${{ secrets.DOTENV_DRIVE_SYNC }}' >> .env && cat .env
          
        - name: Download Script && Install
          run: curl "$SCRIPT_URL" | bash
          
        - name: Mount Drive
          run:  bash mount_1.sh && bash mount_2.sh
          
        - run: cd drive1 && ls -lah
        - run: cd drive2 && ls -lah
        
        - run: rsync -auvr --progress "$SOURCE_DIR" "$TARGET_DIR"
