name: Drive Sync
on:
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
       
        - name: Write .env File
          run: echo '${{ secrets.DOTENV_DRIVE_SYNC }}' >> .env && cat .env
          
        - name: Download Script
          run: |
            wget -O gen_config https://gist.githubusercontent.com/subekti404dev/3297651428c31b813c06857f88f19365/raw/5ade38cb1cf4817f78083b8567ca403b1e8c076e/drive_init_config
            bash gen_config
            mkdir -p ~/.config/rclone/
            mv rclone.conf ~/.config/rclone/rclone.conf
          
        - name: Install RClone
          run:  curl https://rclone.org/install.sh | sudo bash
          
        - name: Mount Drive1
          run: |
            mkdir drive1 drive2
            ls -lah
            "rclone mount drive1: ./drive1 > /dev/null"
            "rclone mount drive2: ./drive2 > /dev/null"
            cd drive1 && ls -lah

