name: Drive Sync
on:
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
       
        - name: Write .env File
          run: echo '${{ secrets.DOTENV_DRIVE_SYNC }}' >> .env && cat .env
          
        - name: Download Script
          run: |
            wget -O gen_config https://gist.githubusercontent.com/subekti404dev/3297651428c31b813c06857f88f19365/raw/5ade38cb1cf4817f78083b8567ca403b1e8c076e/drive_init_config
            bash gen_config

          
        - name: Install RClone
          run:  |
            curl https://rclone.org/install.sh | sudo bash
            mkdir ~/drive1 ~/drive2
          
        - name: Mount Drive1
#           run: |
#             wget -O drive1.service https://gist.githubusercontent.com/subekti404dev/f00170371a236b9c108aefbbe2ad169b/raw/890b1480fbf0d631e4748f4a7ef04af741d56ab4/drive1.service
#             sudo mv drive1.service /etc/systemd/system/drive1.service
#             sudo systemctl start drive1.service
#             cd ~drive1 && ls -lah

          run: |
            cat rclone.conf
            echo "rclone mount --config=rclone.conf drive1: ~/drive1/ > /dev/null &" >> mount.sh
            cat mount.sh
            bash mount.sh
          
        - run: cd ~/drive1 && ls -lah
