
name: Test
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: subekti404dev/github-action-vault-secret@v1
        id: vault
        with:
          base-url: "${{ secrets.VAULT_BASE_URL }}"
          token: "${{ secrets.VAULT_TOKEN }}"
          path: "subekti404dev/test-actions"
          key: "DOTENV_DRIVE_SYNC"
      - name: ECHO
        run: echo "${{ steps.vault.outputs.data }}"
