name: Docker Torrent Download
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Torrent file URL'
        required: true
jobs:
  download:
    runs-on: ubuntu-latest
    container: subekti13/torrent-downloader-v2
    steps:
        - run: torrent config ${{ secrets.RCLONE_CONF_URL }}
                
        - name: Dowload File
          run: torrent download ${{ github.event.inputs.url }} mqtt
      
        - name: LS
          run: tree /data

        - run: sshpass -p ${{ secrets.SCP_PASS }} rsync --progress -avz -e ssh /data/* ${{ secrets.SCP_HOST }}:~/downloads/
          
#         - name: Upload to Drive
#           run: torrent upload 1-u94ApPELl5b3Hpu3SRWReL3KuBzjV7X
