name: Docker Torrent Download
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Torrent file URL'
        required: true
      compress:
        description: 'Compress File After Download'
        
jobs:
  download:
    runs-on: ubuntu-latest
    container: subekti13/torrent-downloader-v2
    steps:
 
        - run: torrent config ${{ secrets.RCLONE_CONF_URL }}
                
        - name: Dowload File
          run: torrent download ${{ github.event.inputs.url }}
      
        - name: LS
          run: tree /data
        
        - name: Compress
          if: github.event.inputs.compress == '1'
          run: compress
          
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.3.1
          with:
           name: SHIT!
           path: .
            

        
