name: Docker Torrent Download
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Torrent file URL'
        required: true
jobs:
  download:
    runs-on: ubuntu-latest
    container: subekti13/torrent-downloader:latest
    steps:
        - run: node /app/getconfig.js ${{ secrets.RCLONE_CONF_URL }}
        
        - name: Dowload File
          run: node /app/download.js ${{ github.event.inputs.url }} mqtt
      
        - name: LS
          run: cd /data && ls -la
          
        - name: Upload to Drive
          run: node /app/upload.js 1-u94ApPELl5b3Hpu3SRWReL3KuBzjV7X
