name: Docker Torrent Download
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Torrent file URL'
        required: true
jobs:
  download:
    runs-on: ubuntu-latest
    container: subekti13/torrent-downloader-v2
    steps:
        - run: torrent config ${{ secrets.RCLONE_CONF_URL }} 1
                
        - name: Dowload File
          run: torrent download ${{ github.event.inputs.url }} mqtt
      
        - name: LS
          run: ls /data
          
        - name: Upload to Drive
          run: torrent upload
